### ISSUE TITLE
ATS Radios

### ISSUE THREAD

**Issue by GreenShadowPT** [Koenvh1/ETS2-City-Coordinate-Retriever#5]
How do i send to you the radios and city coordinates?

**Comment by Koenvh1** [comment]
@04Marcus

**Comment by 04Marcus** [comment]
Do you need help to get the coordinates or do you already have the stations and coordinates?
If so, which area do you want to add?

**Comment by GreenShadowPT** [comment]
I already got the coordinates and stations. I wanna add Great America map, that includes Iowa, Nebraska and South Dakota. (of course cities that arent included in c2c ex: Des Moines, Omaha etc...)
Here is the files : 
https://drive.google.com/file/d/1C2b2-zIxKmJzHkTSfpCt05tK5LA78pud/view?usp=sharing (Radio Stations)
https://drive.google.com/file/d/1oz20aHzpDAEARmXlvKwZNpAlySh5uU6Q/view?usp=sharing (Coordinates)

**Comment by 04Marcus** [comment]
Hmm, I think if we want to add Great America, it has to be deactivated by default. Otherwise it would conflict with C2C and Midwest (50 United).
Do you have the logos too? It's better to have them "local" than to use URLs.

**Comment by GreenShadowPT** [comment]
What do you mean by deactivating? Also i can download all logos if you want.

**Comment by 04Marcus** [comment]
Well I thought of commenting out the Great America stations to avoid these conflicts with C2C, but that isn't possible, because the stations-file isn't local anymore since V3.
But maybe there's no conflict at all if the coordinates of already existing cities like Des Moines in C2C and Great America are the same. I'll take a look at it.

**Comment by GreenShadowPT** [comment]
I didnt include in the radio stations file cities that are in C2C!

**Comment by 04Marcus** [comment]
Yes, I know. :)
But if (for example) C2C Des Moines is way more east than GA Des Moines, you would maybe have a bad reception even if you are in the downtown area.

Unfortunately, as far as I can see, Great America is Payware only, so I can't check the city-coordinates by myself properly. 
I'll add them to Local Radio regardless and will try to check them for conflicting areas in the next few days.

In the meanwhile, please check and change a few things in your station list:

1. The stations have to be in a ascending order regarding FM, HD channels and AM frequencies to keep it realistic. You can check the stations_america.js file [here](https://github.com/Koenvh1/ets2-local-radio/blob/master/web/stations/stations-america.js) to see what I mean.
2. Please use the offical branding names to keep it as accurate as possible - for example:  [KSQY-FM 95.1 MHz in your list is 95.1 K-SKY in reality](https://en.wikipedia.org/wiki/KSQY)
3. Download the station logos, because we need the logos to be "local" to avoid missing images if the Image URL changes 
4. In some cases streaming providers are using "redirection-urls" or so called "mount points" to balance the networktraffic load or to keep streams available on different servers - for example: https://playerservices.streamtheworld.com/api/livestream-redirect/KWWNAMAAC_SC  redirects to  https://14943.live.streamtheworld.com/KWWNAMAAC_SC
You should change the urls to the redirection urls to ensure the availability of the streams.

If you need help, please ask :)

**Comment by GreenShadowPT** [comment]
I will start doing that tommorow. Its kinda of late now here. Thanks for the tips.

**Comment by 04Marcus** [comment]
You're welcome!
Maybe I'll just add the coordinates of the cities and collect the stations, the stream urls and logos by myself. 
--> radio-locator.com or fmscan.org are good sources for example.

That would take some time, but I did that a few times now, so that wouldn't be a big issue ;)

**Comment by GreenShadowPT** [comment]
If you can do it, its ok, but i dont mind doing it too!

**Comment by 04Marcus** [comment]
I'm almost done. You can find the new stations here: https://raw.githubusercontent.com/Koenvh1/ets2-local-radio/master/web/stations/stations-america.js (use Control+F and type greatamerica)

**Comment by GreenShadowPT** [comment]
ok

**Comment by GreenShadowPT** [comment]
really good work! Now Great America users will be able to listen to radio too.

**Comment by 04Marcus** [comment]
I'm done and the new stations are now available in Local Radio.
